# Generated by Django 4.1.2 on 2022-12-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpotifyToken',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=50, null=True)),
                ('user_id', models.IntegerField(default='', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('refresh_token', models.CharField(default='', max_length=300, null=True)),
                ('access_token', models.CharField(default='', max_length=300, null=True)),
                ('expires_in', models.DateTimeField(null=True)),
                ('token_type', models.CharField(default='', max_length=50, null=True)),
            ],
        ),
    ]
