# Generated by Django 4.1.2 on 2022-12-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_url',
            field=models.CharField(default='link', max_length=500, null=True),
        ),
    ]
