# Generated by Django 4.1.2 on 2022-12-04 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_groups_id'),
        ('inscription', '0002_alter_user_last_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='groups.groups'),
        ),
    ]
