# Generated by Django 4.1.2 on 2022-12-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50, null=True, unique=True)),
                ('owner', models.IntegerField(default='', null=True)),
                ('users_amount', models.IntegerField(default=0)),
            ],
        ),
    ]
