# Generated by Django 4.1.2 on 2022-12-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='owner',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
