# Generated by Django 4.1.2 on 2022-12-04 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_alter_groups_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
